name: Build container release images
on:
  push:
    branches:
      - 'community'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      push_to_images: |
        ghcr.io/moonshotedx/mastodon
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      # Always use latest tag for community branch
      flavor: |
        latest=true
      tags: |
        type=raw,value=latest
        type=sha,format=short
    secrets: inherit

  build-image-streaming:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      push_to_images: |
        ghcr.io/moonshotedx/mastodon-streaming
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      # Always use latest tag for community branch
      flavor: |
        latest=true
      tags: |
        type=raw,value=latest
        type=sha,format=short
    secrets: inherit
