name: Build container release images
on:
  workflow_dispatch:
    inputs:
      tag_as_latest:
        description: 'Tag this build as latest?'
        type: boolean
        default: true
      build_streaming:
        description: 'Build streaming image?'
        type: boolean
        default: true
      custom_tag:
        description: 'Optional custom tag (leave empty to use "dev")'
        type: string
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      push_to_images: |
        ghcr.io/moonshotedx/mastodon
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      # Use latest tag based on user input
      flavor: |
        latest=${{ inputs.tag_as_latest }}
      tags: |
        ${{ inputs.tag_as_latest && 'type=raw,value=latest' || '' }}
        type=raw,value=${{ inputs.custom_tag != '' && inputs.custom_tag || 'dev' }}
        type=sha,format=short
    secrets: inherit

  build-image-streaming:
    if: ${{ inputs.build_streaming }}
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      push_to_images: |
        ghcr.io/moonshotedx/mastodon-streaming
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      # Use latest tag based on user input
      flavor: |
        latest=${{ inputs.tag_as_latest }}
      tags: |
        ${{ inputs.tag_as_latest && 'type=raw,value=latest' || '' }}
        type=raw,value=${{ inputs.custom_tag != '' && inputs.custom_tag || 'dev' }}
        type=sha,format=short
    secrets: inherit
